
create extension if not exists "pgcrypto";
create table if not exists public.eumi_users (id uuid primary key default gen_random_uuid(), phone text not null unique, name text not null, password_hash text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.family_links (id uuid primary key default gen_random_uuid(), caregiver_user_id uuid references public.eumi_users(id) on delete cascade, caree_user_id uuid references public.eumi_users(id) on delete cascade, caregiver_phone text, caree_phone text, relation_label text, reverse_relation_label text, requested_by_user_id uuid references public.eumi_users(id) on delete set null, status text not null default 'pending' check (status in ('pending_signup','pending','active','rejected')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.usage_logs (id uuid primary key default gen_random_uuid(), user_id uuid references public.eumi_users(id) on delete cascade, question text, answer text, has_image boolean default false, category text default '기타', place_name text default '미분류', task_name text default '확인하기', short_title text default '화면 질문', folder_key text default '기타__미분류', created_at timestamptz not null default now());
alter table public.eumi_users add column if not exists updated_at timestamptz not null default now();
alter table public.family_links add column if not exists caregiver_user_id uuid references public.eumi_users(id) on delete cascade;
alter table public.family_links add column if not exists caree_user_id uuid references public.eumi_users(id) on delete cascade;
alter table public.family_links add column if not exists caregiver_phone text;
alter table public.family_links add column if not exists caree_phone text;
alter table public.family_links add column if not exists relation_label text;
alter table public.family_links add column if not exists reverse_relation_label text;
alter table public.family_links add column if not exists requested_by_user_id uuid references public.eumi_users(id) on delete set null;
alter table public.family_links add column if not exists status text not null default 'pending';
alter table public.family_links add column if not exists updated_at timestamptz not null default now();
alter table public.usage_logs add column if not exists user_id uuid references public.eumi_users(id) on delete cascade;
alter table public.usage_logs add column if not exists category text default '기타';
alter table public.usage_logs add column if not exists place_name text default '미분류';
alter table public.usage_logs add column if not exists task_name text default '확인하기';
alter table public.usage_logs add column if not exists short_title text default '화면 질문';
alter table public.usage_logs add column if not exists folder_key text default '기타__미분류';
create index if not exists idx_eumi_users_phone on public.eumi_users(phone);
create index if not exists idx_family_links_caregiver on public.family_links(caregiver_user_id);
create index if not exists idx_family_links_caree on public.family_links(caree_user_id);
create index if not exists idx_family_links_status on public.family_links(status);
create index if not exists idx_usage_logs_user_id on public.usage_logs(user_id);
create index if not exists idx_usage_logs_folder_key on public.usage_logs(folder_key);
