-- 이음이 웹앱 2단계: 부모/자녀 계정 + 자동 분류 기록장
-- 실행 위치: Supabase > SQL Editor > New query > Run
-- 중요: 이번 버전은 Supabase Auth 이메일 가입을 쓰지 않고, eumi_users 테이블로 휴대폰번호 로그인합니다.

create extension if not exists pgcrypto;

create table if not exists public.eumi_users (
    id text primary key default gen_random_uuid()::text,
    role text not null check (role in ('parent', 'child')),
    phone text not null,
    name text not null,
    password_hash text not null,
    parent_code text unique,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    unique(role, phone)
);

create table if not exists public.usage_logs (
    id bigint generated by default as identity primary key,
    user_id text not null,
    parent_user_id text,
    parent_code text,
    category text default '기타',
    place_name text default '미분류',
    task_name text default '도움 요청',
    folder_key text default '기타__미분류',
    short_title text,
    question text,
    answer text,
    has_image boolean default false,
    image_name text,
    created_at timestamptz default now()
);

-- 기존 usage_logs가 이미 있는 경우 새 컬럼만 추가합니다.
alter table public.usage_logs add column if not exists parent_user_id text;
alter table public.usage_logs add column if not exists parent_code text;
alter table public.usage_logs add column if not exists category text default '기타';
alter table public.usage_logs add column if not exists place_name text default '미분류';
alter table public.usage_logs add column if not exists task_name text default '도움 요청';
alter table public.usage_logs add column if not exists folder_key text default '기타__미분류';
alter table public.usage_logs add column if not exists short_title text;
alter table public.usage_logs add column if not exists image_name text;

create table if not exists public.family_links (
    id bigint generated by default as identity primary key,
    child_user_id text not null,
    parent_user_id text,
    parent_code text not null,
    parent_name text not null,
    created_at timestamptz default now(),
    unique(child_user_id, parent_code)
);

-- 기존 family_links가 uuid 기반이었던 경우 text 기반으로 바꿉니다.
alter table public.family_links alter column child_user_id type text using child_user_id::text;
alter table public.family_links add column if not exists parent_user_id text;
alter table public.family_links add column if not exists parent_code text;

-- 예전 parent_kakao_id 컬럼이 있으면 parent_code로 복사합니다.
do $$
begin
    if exists (
        select 1 from information_schema.columns
        where table_schema='public' and table_name='family_links' and column_name='parent_kakao_id'
    ) then
        update public.family_links
        set parent_code = coalesce(parent_code, parent_kakao_id)
        where parent_code is null;
    end if;
end $$;

create index if not exists idx_eumi_users_role_phone on public.eumi_users(role, phone);
create index if not exists idx_eumi_users_parent_code on public.eumi_users(parent_code);
create index if not exists idx_usage_logs_parent_user_id on public.usage_logs(parent_user_id);
create index if not exists idx_usage_logs_parent_code on public.usage_logs(parent_code);
create index if not exists idx_usage_logs_folder_key on public.usage_logs(folder_key);
create index if not exists idx_family_links_child_user_id on public.family_links(child_user_id);
create index if not exists idx_family_links_parent_code on public.family_links(parent_code);

-- 보안: 앱은 Streamlit Secrets의 SUPABASE_SERVICE_ROLE_KEY로 접근합니다.
-- service_role은 RLS를 우회하므로, 브라우저에 노출하지 말고 GitHub에도 절대 올리지 마세요.
alter table public.eumi_users enable row level security;
alter table public.usage_logs enable row level security;
alter table public.family_links enable row level security;

-- 기존에 테스트용으로 열어둔 anon 정책은 제거합니다.
drop policy if exists "usage_logs_insert_for_webapp" on public.usage_logs;
drop policy if exists "usage_logs_select_for_dashboard" on public.usage_logs;
drop policy if exists "family_links_select_own" on public.family_links;
drop policy if exists "family_links_insert_own" on public.family_links;
drop policy if exists "family_links_delete_own" on public.family_links;
