-- 이음이 웹앱 MVP용 Supabase 테이블
-- 이미 usage_logs, family_links 테이블이 있으면 새로 만들 필요는 없습니다.
-- 권한 오류가 날 때만 아래 정책을 확인하세요.

create table if not exists public.usage_logs (
    id bigint generated by default as identity primary key,
    user_id text not null,
    question text,
    answer text,
    has_image boolean default false,
    created_at timestamptz default now()
);

create table if not exists public.family_links (
    id bigint generated by default as identity primary key,
    child_user_id uuid not null,
    parent_kakao_id text not null,
    parent_name text not null,
    created_at timestamptz default now()
);

alter table public.usage_logs enable row level security;
alter table public.family_links enable row level security;

-- 부모님 웹앱은 로그인 없이 사용하므로 usage_logs insert/select가 필요합니다.
-- MVP 테스트용입니다. 운영 전에는 개인정보 최소화 정책을 다시 점검하세요.
drop policy if exists "usage_logs_insert_for_webapp" on public.usage_logs;
create policy "usage_logs_insert_for_webapp"
on public.usage_logs
for insert
to anon, authenticated
with check (true);

drop policy if exists "usage_logs_select_for_dashboard" on public.usage_logs;
create policy "usage_logs_select_for_dashboard"
on public.usage_logs
for select
to anon, authenticated
using (true);

-- 자녀 계정은 본인이 만든 family_links만 볼 수 있게 합니다.
drop policy if exists "family_links_select_own" on public.family_links;
create policy "family_links_select_own"
on public.family_links
for select
to authenticated
using (child_user_id = auth.uid());

drop policy if exists "family_links_insert_own" on public.family_links;
create policy "family_links_insert_own"
on public.family_links
for insert
to authenticated
with check (child_user_id = auth.uid());

drop policy if exists "family_links_delete_own" on public.family_links;
create policy "family_links_delete_own"
on public.family_links
for delete
to authenticated
using (child_user_id = auth.uid());
